import Head from "next/head";
import Layout from "../components/Layout";
import css from '../styles/Home.module.css'
import Hero from "../components/Hero";
import { client } from "../lib/client";
export default function Home({ pizzas }) {

  return (
    <Layout pizzas={pizzas} >
      <div >
        <Head >
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main >
        </main>
      </div>
    </Layout>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type=="pizza"]';
  const pizzas = await client.fetch(query)
  return {
    props: {
      pizzas
    }
  }
}
